# Auto-generated config - DO NOT EDIT MANUALLY
# Edit config.json instead

CALCULATION_METHOD="20"
CALCULATION_SCHOOL="0"

ZAKAT_CURRENCY="IDR"
ZAKAT_GOLD_THRESHOLD="85"
ZAKAT_API_KEY="${ZAKAT_API_KEY:-k8090qKpozfSNHV8MvODYtbK8E24M1yveTiAXh0zipjzDtdF}"

TIMEZONE="UTC"
QURAN_LANGUAGE="id"
